### ISSUE TITLE
tf models of mobileface

### ISSUE THREAD

**Issue by LuGuo1920** [papermsucode/advhat#11]
Can you provide tf models of r50 r34 and mobileface? I try to change  from mxnet models in  mobile-ZOO you provide  to tf models. But I can't gain  tf-models having same nodes and names of nodes with yours.

**Comment by Polkach** [comment]
I'm afraid that it isn`t possible due to the current transferring policy of our lab.
We were doing as follows:
1) Save weights of the mxnet model as numpy arrays.
2) Build exactly the same architecture as in the ArcFace model (https://github.com/lutzroeder/netrmay be helpful for architecture visualization)
3) Initialize the weights of the built network using saved weights :)

**Comment by LuGuo1920** [comment]
I'm still not particularly clear about how you do it. I use mmdnn to transform. The nodes I get are different from your model‘s. Do you remove  FC layer?

**Comment by Polkach** [comment]
We didn't use any automatic library to transform the MXNet model to TensorFlow. We did it manually: as I wrote before, we created exactly the same graph in TensorFlow and initialized it with the pretrained weights from the MXNet model (I'll initialize the procedure of additional code sharing but it will take time).
Note that there is no classifying FC-layer in the pretrained networks by InsightFace. This is because we don't need it during inference and testing.

**Comment by LuGuo1920** [comment]
Oh ,I see now. But I visualize the architecture of r100.pb that you provide and  [LResNet100E-IR](https://github.com/deepinsight/insightface/wiki/Model-Zoo) .As the picture shows, they are not the same. 
![r100](https://user-images.githubusercontent.com/16723578/108085126-f52eba00-70af-11eb-8c8c-f5b7b1c3e7bb.PNG)

![官方](https://user-images.githubusercontent.com/16723578/108085161-feb82200-70af-11eb-9ad6-347c803c9fd8.PNG)

**Comment by Polkach** [comment]
Visualization of the *.pb file is not very useful :) I will share a notebook with a convertation code in the nearest future. I'll  write a message here after commit

**Comment by Polkach** [comment]
@LuGuo1920 , you can find the demonstration notebook in the latest commit

**Comment by LuGuo1920** [comment]
I see the notebook you just commit. Thank you so much for your sharing ,replay and message. I don't know how to express my appreciations for you.
