### ISSUE TITLE
Steps to Test the Whole Project?

### ISSUE THREAD

**Issue by cserezwan** [papermsucode/advhat#14]
Hello, is it possible to provide proper documentation or guideline to test the whole project?
Suppose, what are the pre-requisites and steps needed to follow?
Thanks.

**Comment by Polkach** [comment]
Dear @cserezwan ,

Honestly, we are not planning to prepare any additional materials. We believe that the paper itself and all READMEs are enough to reproduce our experiments. Since this is not a production code but a research code, we don't make it workable in each possible environment. However, if you meet any issues, feel free to ask for our help!

Note that the README in the root folder isn't the onliest. Other READMEs are in subdirectories.
